#!/usr/bin/env bash

#initialize variables
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#process arguments

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -s|--size)
    SIZE="$2"
    shift # past argument
    shift # past value
    ;;
    -p|--path)
    OUTPUTPATH="$2"
    shift # past argument
    shift # past value
    ;;
    -t|--tag)
    TAG="$2"
    shift # past argument
    shift # past value
    ;;
    --default)
    DEFAULT=YES
    shift # past argument
    ;;
    *)    # unknown option
    COLOR+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${COLOR[@]}" # restore positional parameters

echo SIZE = ${SIZE}
echo OUTPUTPATH = ${OUTPUTPATH}
echo TAG = ${TAG}
echo DEFAULT = ${DEFAULT}
echo COLOR = ${COLOR}

#create color directory and copy all the files in
mkdir ./${COLOR}

cp ${SOURCE_DIR}/node_modules/octicons/build/svg/* ./${COLOR}

#edit the svgs to add the color and add the tag to the filename
for f in ./${COLOR}/*.svg; do
  sed -i 's/path/path fill='${COLOR}'/g' $f
  REGEX_STRING = "s/.svg/-${TAG}.svg/g"
  mv "$f" "$(sed "${REGEX_STRING}"  <<< "$f")"
done
